version: "3"
services:
  # SQLのサービス
  db:
    image: mysql:8.0
    container_name: "spring_db"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d # テーブル作成やデータの初期化をする設定
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: "spring_test"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"

  # springアプリケーションのサービス
  spring:
    container_name: "spring"
    restart: always
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
    volumes:
      - ./:/app/:cached
    working_dir: /app
    build: .
